name: Manual Cloudsmith NPM Workflow

# Trigger manually from GitHub UI
on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Configure NPM to use Cloudsmith
        run: |
          echo "registry=https://npm.cloudsmith.io/testcheck/product-demo/" > .npmrc
          echo "//npm.cloudsmith.io/testcheck/product-demo/:_authToken=${{ secrets.CLOUDSMITH_TOKEN }}" >> .npmrc
     

      - name: Install dependencies from Cloudsmith
        run: npm install colors
      - name: print package-lock.json file
        run: cat package-lock.json

      - name: Pack the project
        run: npm pack

      - name: Install Cloudsmith CLI
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install --upgrade cloudsmith-cli

      - name: Push package to Cloudsmith
        run: |
          PACKAGE_FILE=$(ls *.tgz)
          cloudsmith push npm testcheck/product-demo "$PACKAGE_FILE"
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_TOKEN }}
